[2025-05-06T03:05:42.936+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-06T03:05:42.957+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2025-05-06T03:05:42.296846+00:00 [queued]>
[2025-05-06T03:05:42.974+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2025-05-06T03:05:42.296846+00:00 [queued]>
[2025-05-06T03:05:42.978+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-06T03:05:43.001+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run> on 2025-05-06 03:05:42.296846+00:00
[2025-05-06T03:05:43.013+0000] {standard_task_runner.py:72} INFO - Started process 1582 to run task
[2025-05-06T03:05:43.018+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2025-05-06T03:05:42.296846+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmph_rjh26g']
[2025-05-06T03:05:43.024+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask dbt_run
[2025-05-06T03:05:43.100+0000] {task_command.py:467} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2025-05-06T03:05:42.296846+00:00 [running]> on host 4bf74f6ca137
[2025-05-06T03:05:43.203+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T03:05:42.296846+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T03:05:42.296846+00:00'
[2025-05-06T03:05:43.206+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-06T03:05:43.232+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T03:05:43.234+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/tesla_project --project-dir /opt/***/tesla_project']
[2025-05-06T03:05:43.250+0000] {subprocess.py:86} INFO - Output:
[2025-05-06T03:05:45.286+0000] {subprocess.py:93} INFO - [0m03:05:45  Running with dbt=1.8.7
[2025-05-06T03:05:46.286+0000] {subprocess.py:93} INFO - [0m03:05:46  Registered adapter: snowflake=1.8.1
[2025-05-06T03:05:46.431+0000] {subprocess.py:93} INFO - [0m03:05:46  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-05-06T03:05:47.923+0000] {subprocess.py:93} INFO - [0m03:05:47  Encountered an error:
[2025-05-06T03:05:47.925+0000] {subprocess.py:93} INFO - Compilation Error
[2025-05-06T03:05:47.926+0000] {subprocess.py:93} INFO -   Snapshot 'snapshot.tesla_project.final_raw_snapshot' (snapshots/final_raw_snapshot.sql) depends on a source named 'raw.final_raw_table' which was not found
[2025-05-06T03:05:48.616+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-06T03:05:48.628+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-06T03:05:48.634+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2025-05-06T03:05:42.296846+00:00, execution_date=20250506T030542, start_date=20250506T030542, end_date=20250506T030548
[2025-05-06T03:05:48.648+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-06T03:05:48.650+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 30 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 1582)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-06T03:05:48.669+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-06T03:05:48.688+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-06T03:05:48.694+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
