[2025-05-06T01:31:50.598+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-06T01:31:50.625+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_stock_sentiment_final_etl.merge_stock_and_sentiment_to_raw scheduled__2025-05-04T02:30:00+00:00 [queued]>
[2025-05-06T01:31:50.647+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_stock_sentiment_final_etl.merge_stock_and_sentiment_to_raw scheduled__2025-05-04T02:30:00+00:00 [queued]>
[2025-05-06T01:31:50.648+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-06T01:31:50.677+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): merge_stock_and_sentiment_to_raw> on 2025-05-04 02:30:00+00:00
[2025-05-06T01:31:50.690+0000] {standard_task_runner.py:72} INFO - Started process 2464 to run task
[2025-05-06T01:31:50.710+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_stock_sentiment_final_etl', 'merge_stock_and_sentiment_to_raw', 'scheduled__2025-05-04T02:30:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl.py', '--cfg-path', '/tmp/tmpo3mdxp5n']
[2025-05-06T01:31:50.714+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask merge_stock_and_sentiment_to_raw
[2025-05-06T01:31:51.075+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_stock_sentiment_final_etl.merge_stock_and_sentiment_to_raw scheduled__2025-05-04T02:30:00+00:00 [running]> on host ccc68f7ecbda
[2025-05-06T01:31:51.156+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_stock_sentiment_final_etl' AIRFLOW_CTX_TASK_ID='merge_stock_and_sentiment_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-04T02:30:00+00:00'
[2025-05-06T01:31:51.158+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-06T01:31:51.404+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-06T01:31:51.506+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-06T01:31:51.810+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-06T01:31:51.812+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tesla_stock_etl.py", line 161, in merge_stock_and_sentiment_to_raw
    raise e
  File "/opt/airflow/dags/tesla_stock_etl.py", line 112, in merge_stock_and_sentiment_to_raw
    cur.execute(f"""
  File "/home/airflow/.local/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 1087, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 284, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 339, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 215, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (42S02): 01bc281b-0305-24f3-0008-027b0006e652: SQL compilation error:
Object 'DEV.RAW.TESLA_STOCK_DATA' does not exist or not authorized.
[2025-05-06T01:31:51.822+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=tesla_stock_sentiment_final_etl, task_id=merge_stock_and_sentiment_to_raw, run_id=scheduled__2025-05-04T02:30:00+00:00, execution_date=20250504T023000, start_date=20250506T013150, end_date=20250506T013151
[2025-05-06T01:31:51.840+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-06T01:31:51.841+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task merge_stock_and_sentiment_to_raw (002003 (42S02): 01bc281b-0305-24f3-0008-027b0006e652: SQL compilation error:
Object 'DEV.RAW.TESLA_STOCK_DATA' does not exist or not authorized.; 2464)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tesla_stock_etl.py", line 161, in merge_stock_and_sentiment_to_raw
    raise e
  File "/opt/airflow/dags/tesla_stock_etl.py", line 112, in merge_stock_and_sentiment_to_raw
    cur.execute(f"""
  File "/home/airflow/.local/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 1087, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 284, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 339, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 215, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (42S02): 01bc281b-0305-24f3-0008-027b0006e652: SQL compilation error:
Object 'DEV.RAW.TESLA_STOCK_DATA' does not exist or not authorized.
[2025-05-06T01:31:51.887+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-06T01:31:51.904+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-06T01:31:51.913+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
